"""Generate the reproduction workspace: issue.md, metadata.json, reproduce.sh, Dockerfile."""

from __future__ import annotations

import json
from pathlib import Path

from issue2repro.models import Analysis

_DOCKER_BASES = {"python": "python:3.12-slim", "node": "node:20-slim"}


def render_issue_md(analysis: Analysis) -> str:
    issue = analysis.issue
    lines = [
        f"# {issue.title}",
        "",
        f"Source: {issue.ref.issue_url}",
        "",
        issue.body or "(no body)",
    ]
    for i, comment in enumerate(issue.comments, start=1):
        lines += ["", "---", "", f"## Comment {i}", "", comment]
    return "\n".join(lines) + "\n"


def _scoped_test_command(analysis: Analysis, mapped_paths: list[str]) -> str:
    """The detected test command, scoped to trace-implicated files when possible.

    Scoping only applies to pytest, and only to implicated files that are
    themselves test files; pointing pytest at library modules collects nothing.
    """
    test_command = analysis.project.test_command or ""
    if "pytest" not in test_command:
        return test_command
    test_files = [
        p
        for p in mapped_paths
        if p.endswith(".py") and ("test" in Path(p).name or p.startswith(("tests/", "test/")))
    ]
    if test_files:
        return f"{test_command} {' '.join(test_files)}"
    return test_command


def render_reproduce_sh(analysis: Analysis, mapped_paths: list[str]) -> str:
    """Build reproduce.sh.

    Explicit commands from the issue win. Otherwise fall back to the
    manifest install steps plus the detected test command, scoped to files
    the stack trace implicates. Python runs inside a workspace-local venv
    so pip installs never touch the caller's environment.
    """
    issue = analysis.issue
    project = analysis.project
    lines = [
        "#!/usr/bin/env bash",
        f"# Generated by issue2repro for {issue.ref.slug}",
        f"# Issue: {issue.ref.issue_url}",
        "#",
        "# WARNING: this script executes code from the cloned repository.",
        "# Read it before running. A nonzero exit usually means the bug reproduced.",
        "set -euo pipefail",
        'WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    ]
    if project.language == "python":
        lines += [
            "",
            "# Isolated environment so installs do not touch your system Python.",
            'if [ ! -d "$WORKSPACE/.venv" ]; then python3 -m venv "$WORKSPACE/.venv"; fi',
            '. "$WORKSPACE/.venv/bin/activate"',
        ]
    lines += ["", 'cd "$WORKSPACE/source"', ""]

    if analysis.signals.commands:
        lines.append("# Explicit reproduction steps taken from the issue text.")
        lines.extend(analysis.signals.commands)
    else:
        lines.append("# No explicit steps in the issue; running the detected test command.")
        lines.extend(project.install_commands)
        scoped = _scoped_test_command(analysis, mapped_paths)
        if scoped:
            lines.append(scoped)
        else:
            lines += [
                'echo "issue2repro could not detect a test command for this project." >&2',
                "exit 2",
            ]
    return "\n".join(lines) + "\n"


def render_dockerfile(analysis: Analysis) -> str:
    """Best-effort Dockerfile for the detected ecosystem.

    It sets up the right base image and manifest install steps; it will not
    magically reproduce every issue (system deps, services, etc. are on you).
    """
    project = analysis.project
    base = _DOCKER_BASES.get(project.language or "", "debian:bookworm-slim")
    lines = [
        f"# Generated by issue2repro for {analysis.issue.ref.slug} (best effort)",
        f"FROM {base}",
        "WORKDIR /repro",
        "COPY source/ ./source/",
        "COPY reproduce.sh issue.md metadata.json ./",
        "WORKDIR /repro/source",
    ]
    if project.language == "python":
        for cmd in analysis.project.install_commands:
            lines.append(f"RUN {cmd}")
    elif project.language == "node":
        lines.append("RUN npm install")
    else:
        lines.append("# Unknown ecosystem: no install steps inferred.")
    lines += [
        "WORKDIR /repro",
        'CMD ["bash", "reproduce.sh"]',
    ]
    return "\n".join(lines) + "\n"


def write_workspace(analysis: Analysis, mapped_paths: list[str], out_dir: Path) -> list[Path]:
    """Write everything except source/ (the clone is moved in by the CLI)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    issue_md = out_dir / "issue.md"
    issue_md.write_text(render_issue_md(analysis))
    written.append(issue_md)

    metadata = out_dir / "metadata.json"
    payload = analysis.to_metadata()
    payload["trace_paths_in_clone"] = mapped_paths
    metadata.write_text(json.dumps(payload, indent=2) + "\n")
    written.append(metadata)

    reproduce = out_dir / "reproduce.sh"
    reproduce.write_text(render_reproduce_sh(analysis, mapped_paths))
    reproduce.chmod(0o755)
    written.append(reproduce)

    dockerfile = out_dir / "Dockerfile"
    dockerfile.write_text(render_dockerfile(analysis))
    written.append(dockerfile)

    return written
